### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by pomax96** [pomax96/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by dasha-korotkykh** [comment]
Хей, привіт! Якщо ти складаєш резюме про себе чи улюбленого персонажа/людину, тобі потрібно написати цей контент самій, я буду рада його продивитися і порадити щось, якщо буде потрібно. Якщо ти складаєш сторінку на замовлення Рю або Дональда, тобі потрібно взяти інформацію з їхніх файлів відповідно, які вказані в описі завдання. Знаєш де лінки на ті файли, чи скинути тобі? :)
P.S. те саме стосується і інших issues

**Comment by pomax96** [comment]
Привіт, ок, дякую)
